- name: Installing stow
  apt: name=stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:johnmarco123/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  become: yes
  become_method: su
  become_user: john
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
